'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7aTk470d3Bg=")>  _
        Public Property FTPEncryptedUserName() As String
            Get
                Return CType(Me("FTPEncryptedUserName"),String)
            End Get
            Set
                Me("FTPEncryptedUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TEp1ggdQy0JPwJoOtUgo1A==")>  _
        Public Property FTPEncryptedPassword() As String
            Get
                Return CType(Me("FTPEncryptedPassword"),String)
            End Get
            Set
                Me("FTPEncryptedPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Production")>  _
        Public Property Environment() As String
            Get
                Return CType(Me("Environment"),String)
            End Get
            Set
                Me("Environment") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentWebSite() As String
            Get
                Return CType(Me("CurrentWebSite"),String)
            End Get
            Set
                Me("CurrentWebSite") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://gis.menv.com/MESTraining/upload.aspx")>  _
        Public Property UriString() As String
            Get
                Return CType(Me("UriString"),String)
            End Get
            Set
                Me("UriString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WebClientTimeout() As Integer
            Get
                Return CType(Me("WebClientTimeout"),Integer)
            End Get
            Set
                Me("WebClientTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MESTraining")>  _
        Public Property DefaultTrainingSiteName() As String
            Get
                Return CType(Me("DefaultTrainingSiteName"),String)
            End Get
            Set
                Me("DefaultTrainingSiteName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tHdr6L1XtyzHdPo3VJoOVHsX64u/r4YuS6QeDvjVP54VdvrTlD+vWwz1W9deA6UPza0LBmm0NvG6IftKc"& _ 
            "Pxkez7rJXDMRG2p")>  _
        Public Property DefaultEncryptedString() As String
            Get
                Return CType(Me("DefaultEncryptedString"),String)
            End Get
            Set
                Me("DefaultEncryptedString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://gis.menv.com/MESTraining/")>  _
        Public Property DefaultURL() As String
            Get
                Return CType(Me("DefaultURL"),String)
            End Get
            Set
                Me("DefaultURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MESTraining")>  _
        Public Property TrainingSiteName() As String
            Get
                Return CType(Me("TrainingSiteName"),String)
            End Get
            Set
                Me("TrainingSiteName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tHdr6L1XtyzHdPo3VJoOVHsX64u/r4YuS6QeDvjVP54VdvrTlD+vWwz1W9deA6UPza0LBmm0NvG6IftKc"& _ 
            "Pxkez7rJXDMRG2p")>  _
        Public Property EncryptedString() As String
            Get
                Return CType(Me("EncryptedString"),String)
            End Get
            Set
                Me("EncryptedString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://gis.menv.com/MESTraining/")>  _
        Public Property URL() As String
            Get
                Return CType(Me("URL"),String)
            End Get
            Set
                Me("URL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\inetpub\wwwroot\MES\MESTraining\MESTraining\Media\")>  _
        Public Property DefaultMediaDir() As String
            Get
                Return CType(Me("DefaultMediaDir"),String)
            End Get
            Set
                Me("DefaultMediaDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\inetpub\wwwroot\MES\MESTraining\MESTraining\Media\")>  _
        Public Property MediaDir() As String
            Get
                Return CType(Me("MediaDir"),String)
            End Get
            Set
                Me("MediaDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://gis.menv.com/MES/DataAccessWS/")>  _
        Public Property WebServiceURL() As String
            Get
                Return CType(Me("WebServiceURL"),String)
            End Get
            Set
                Me("WebServiceURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://gis.menv.com/MES/DataAccessWS/DataAccessWS.asmx")>  _
        Public ReadOnly Property MESTraining_com_menv_gis_DataAccessWS() As String
            Get
                Return CType(Me("MESTraining_com_menv_gis_DataAccessWS"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MESTraining.My.MySettings
            Get
                Return Global.MESTraining.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
