'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Index3Col

    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''PrimaryLeftCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrimaryLeftCol As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''PrimaryMiddleCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrimaryMiddleCol As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''PrimaryRightCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrimaryRightCol As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''UpperSecondaryConentBlockLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpperSecondaryConentBlockLeft As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''UpperSecondaryConentBlockMiddleLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpperSecondaryConentBlockMiddleLeft As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''UpperSecondaryConentBlockMiddleRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpperSecondaryConentBlockMiddleRight As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''UpperSecondaryConentBlockRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpperSecondaryConentBlockRight As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''LowerSecondaryConentBlockMiddle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LowerSecondaryConentBlockMiddle As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''LowerSecondaryConentBlockRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LowerSecondaryConentBlockRight As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
