'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Main

    '''<summary>
    '''ctl00_css_IE8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_css_IE8 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ctl00_css_IE7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_css_IE7 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ctl00_Link1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_Link1 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ctl00_Link2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_Link2 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ctl00_Link3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_Link3 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ctl00_Link4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_Link4 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ctl00_Link5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_Link5 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ctl00_Link9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00_Link9 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''css_IE8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents css_IE8 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''css_IE7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents css_IE7 As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''SlimBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlimBanner As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''HeaderBannerBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderBannerBlock As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''DNS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DNS As Global.System.Web.UI.WebControls.SiteMapDataSource

    '''<summary>
    '''PrimaryNavigationMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrimaryNavigationMenu As Global.MESTraining.MDGOV.PrimaryNavMenu

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''FooterLinksData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FooterLinksData As Global.System.Web.UI.WebControls.SiteMapDataSource

    '''<summary>
    '''FooterLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FooterLinks As Global.MESTraining.MDGOV.FooterMenu

    '''<summary>
    '''FooterAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FooterAddress As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FooterPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FooterPhone As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SocialNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SocialNav As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''SocialMediaButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SocialMediaButtons As Global.MESTraining.MDGOV.SocialMedia
End Class
